server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      rotate: true
      pattern: '%h %l %u %t "%r" %s %b %D'
    
mirrorpage:
  root: '/opt/mirrorpage/produtos'
  #root: 'C:/mirrorpage/Produtos'
  #root: '/opt/mirrorpage/produtos'
  
  jwt:
    secret: "0123456789ZOLDYCKILLYUA9876543210"  # use algo forte!
    access-minutes: 30
    refresh-days: 7

app:
  log:
    path: '/opt/mirrorpage/conf/ServerLogs.txt'
    #path: 'C:/mirrorpage/Conf/ServerLogs.txt'
    #path: '/opt/mirrorpage/conf/ServerLogs.txt'
    

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/mirrorpage?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=America/Sao_Paulo'
    username: mirror
    password: Mirror@2025
#    password: Mirror@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true 
    clean-disabled: true

# (opcional) log mais verboso ao iniciar
logging:
  level:
    com.app.mirrorpage: DEBUG

    org.springframework.web: INFO
    org.springframework.security: INFO
    org.flywaydb.core: INFO
    org.hibernate.SQL: INFO